config/routes.rb
Rails.application.routes.draw do
  get "new", to: "games#new"
  post "score", to: "games#score"
  get "continue", to: "games#continue" # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'open-uri'
require 'json'

class GamesController < ApplicationController

  def new
    cookies[:score] = 0
    @letters = Array.new(10) { ("A".."Z").to_a.sample }
  end

  def continue
    cookies[:score] = 0 unless cookies[:score]
    @letters = Array.new(10) { ("A".."Z").to_a.sample }
  end

  def score
    @game_score = 0
    grid = params[:grid].split("")
    if valid_word?(params[:answer]) && included?(params[:answer], grid)
      @result = "Congratulations <strong>#{params[:answer]}</strong> is a valid English word!"
      @game_score = params[:answer].length * 2
      cookies[:score] = cookies[:score].to_i + @game_score
    elsif valid_word?(params[:answer]) && !included?(params[:answer], grid)
      @result = "Sorry but <strong>#{params[:answer]}</strong> can't be build out of #{grid.join(" ")}"
    else
      @result = "Sorry but <strong>#{params[:answer]}</strong> doest not seem to be a valid English word"
    end
  end

  def valid_word?(attempt)
    file_path = "https://wagon-dictionary.herokuapp.com/#{attempt}"
    JSON.parse(open(file_path).read)["found"]
  end

  def included?(attempt, grid)
    attempt.upcase.chars.all? { |letter| attempt.upcase.count(letter) <= grid.count(letter) }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/continue.html.erb
<h1>Continue Game</h1>

<ul>
  <% @letters.each do |letter| %>
    <li><%= letter.capitalize %></li>
  <% end %>
</ul>

<p>What is the longest word you can find?</p>

<form action="/score" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="answer">
  <input type="submit" value="Submit" class="submitbtn">
  <input type="hidden" value=<%=@letters.join("")%> name="grid">
</form>


<p>Your Current Score is = <%=cookies[:score]%></p>

app/views/games/new.html.erb
<h1>New Game</h1>

<ul>
  <% @letters.each do |letter| %>
    <li><%= letter.capitalize %></li>
  <% end %>
</ul>

<p>What is the longest word you can find?</p>

<form action="/score" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="answer">
  <input type="submit" value="Submit" class="submitbtn">
  <input type="hidden" value=<%=@letters.join("")%> name="grid">
</form>

app/views/games/score.html.erb
<h1><strong>Result</strong></h1>

<p><%= sanitize @result%></p>

<p><strong>Game Score = <%=@game_score%></strong></p>
<p><strong>Total Score = <%=cookies[:score] %></strong></p>
<%= link_to "Start Playing Again", new_path %>

<%= link_to "Continue Playing", continue_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>